[description]
skill_name = "ChatSkill.ChatUser"
skill_description = "The skill is the ability to handle conversations with a user, responding to their input and providing appropriate responses."
output_name = "response"
output_description = "A response to the user's input, based on the conversation context and the user's attitude."
output_uses = "Can be used to provide a natural conversation experience to the user."
output_type = "text/string"
[[description.arguments]]
argument_name = "person"
argument_identifier = "{{$person}}"
argument_description = "The name of the person interacting with the AI assistant."
argument_sources = "The user's name can be directly provided, inferred from previous interactions, or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "attitude"
argument_identifier = "{{$attitude}}"
argument_description = "The attitude of the user interacting with the AI assistant."
argument_sources = "The user's attitude can be inferred from previous interactions or obtained from a user profile."
argument_type = "text/string"

[[description.arguments]]
argument_name = "user"
argument_identifier = "{{$user}}"
argument_description = "The user's tag or name in the conversation."
argument_sources = "The user's name or tag can be directly provided or extracted from conversation/dialogue."
argument_type = "text/string"

[[description.arguments]]
argument_name = "bot"
argument_identifier = "{{$bot}}"
argument_description = "The bots's tag or name in the conversation."
argument_sources = "The bots's name or tag is set by the system or pulled from hisorical interactions."
argument_type = "text/string"

[[description.arguments]]
argument_name = "question"
argument_identifier = "{{$question}}"
argument_description = "The question the AI assistant should ask the user."
argument_sources = "The question can be provided by the user or inferred from the conversation context."
argument_type = "text/string"

[[description.arguments]]
argument_name = "history"
argument_identifier = "{{$history}}"
argument_description = "The conversation history between the user and the AI assistant."
argument_sources = "The conversation history can be extracted from the conversation/dialogue or provided by a system tracking it."
argument_type = "text/string"

[[description.arguments]]
argument_name = "input"
argument_identifier = "{{$input}}"
argument_description = "The user's response to the AI assistant's question."
argument_sources = "The user's response can be directly provided or extracted from conversation/dialogue."
argument_type = "text/string"

